name: sqlite_storage
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  sqflite: ^2.3.3+1
  domain_models:
    path: ../domain_models

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
