name: sqlite_storage
publish_to: none

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  sqflite: ^2.3.0
  path: ^1.8.3
  domain_models:
    path: ../domain_models

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
