name: recording_service
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.2
  flutter: '>=3.47.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_foreground_task: ^11.0.2
  domain_models:
    path: ../domain_models
  foreground_location_service:
    path: ../foreground_location_service
  routes_repository:
    path: ../routes_repository
  sqlite_storage:
    path: ../sqlite_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.2
