name: geocoding_manager
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  geocoding: ^3.0.0
  meta: ^1.15.0
  osm_nominatim: ^3.0.1
  domain_models:
    path: ../domain_models
  sqlite_storage:
    path: ../sqlite_storage


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
