name: domain_models
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0
  equatable: ^2.0.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
