name: footprint
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1

  domain_models:
    path: packages/domain_models
  #  location_service:
  #    path: packages/location_service
  foreground_location_service:
    path: packages/foreground_location_service
  geocoding_repository:
    path: packages/geocoding_repository
  routes_repository:
    path: packages/routes_repository
  component_library:
    path: packages/component_library
  map:
    path: packages/features/map
  route_list:
    path: packages/features/route_list
  sqlite_storage:
    path: packages/sqlite_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
