name: foreground_location_service
publish_to: 'none'

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  uuid: ^4.2.2
  flutter_foreground_task: ^8.3.0
  domain_models:
    path: ../domain_models

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
