name: foreground_location_service
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_foreground_task: ^8.6.0
  geolocator: ^13.0.1
  uuid: ^4.4.2
  domain_models:
    path: ../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

