name: map
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_map: ^7.0.2
  google_fonts: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_animations: ^0.7.0
  flutter_foreground_task: ^8.3.1
  permission_handler: ^11.3.1
  meta: ^1.10.0
  domain_models:
    path: ../../domain_models
  routes_repository:
    path: ../../routes_repository
  geocoding_repository:
    path: ../../geocoding_repository
  component_library:
    path: ../../component_library
  foreground_location_service:
    path: ../../foreground_location_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
