name: map
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_map: ^7.0.2
  google_fonts: ^6.2.1
  latlong2: ^0.9.1
  flutter_map_animations: ^0.7.1
  flutter_foreground_task: ^8.6.0
  meta: ^1.15.0
  domain_models:
    path: ../../domain_models
  routes_repository:
    path: ../../routes_repository
  geocoding_manager:
    path: ../../geocoding_manager
  component_library:
    path: ../../component_library
  foreground_location_service:
    path: ../../foreground_location_service


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
