name: foreground_task_service
publish_to: 'none'

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_foreground_task: ^8.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
