name: location_service
publish_to: none

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  meta: ^1.10.0
  uuid: ^4.2.2
  domain_models:
    path: ../domain_models

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
