name: location_repository
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  geolocator: ^10.1.0
  meta: ^1.10.0
  uuid: ^4.2.2
  domain_models:
    path: ../domain_models

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

#  fav_qs_api:
#    path: ../fav_qs_api
#    key_value_storage:
#      path: ../key_value_storage
#    domain_models:
#      path: ../domain_models
