name: routes_repository
publish_to: none

environment:
  sdk: '>=3.4.0'

dependencies:
  domain_models:
    path: ../domain_models
  local_storage:
    path: ../local_storage

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0