name: routes_repository
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  sqlite_storage:
    path: ../sqlite_storage

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
