name: routes_repository
publish_to: none

environment:
  sdk: '>=3.4.0'

dependencies:
  meta: ^1.10.0
  domain_models:
    path: ../domain_models
  sqlite_storage:
    path: ../sqlite_storage

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0