name: component_library
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.2
  flutter: '>=3.47.2'

dependencies:
  domain_models:
    path: ../domain_models
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  url_launcher: ^6.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed.ttf
